Whatever said is enough. 
Product page, add to cart, then checkout with invoice. No pdf, only UI
Carousel or any ui enhancement is upto you
Proper spec I'm not looking. You can decide the data fields





switch(catagory) {
    case null:
      // code block
      product.childNodes.forEach(data=> {
        // console.log(data)
    if(data.firstChild !== null){
        data.classList.add("d-flex");
        }
    });
      break;
    case null:
      // code block
      break;
    default:
      // code block
  }

}